export const mockProducts = [
  {
    id: 1,
    name: "Khóa học IELTS 7.0+ với giáo viên bản ngữ",
    price: 1500000,
    image: "https://picsum.photos/300/200?random=1",
    shortDescription: "Luyện thi IELTS toàn diện với giáo viên Anh/Mỹ",
    fullDescription: "Khóa học IELTS chuyên sâu giúp bạn đạt band 7.0+ trong 3 tháng. Học trực tiếp với giáo viên bản ngữ, luyện tập 4 kỹ năng toàn diện.",
    rating: 4.8,
    reviews: 234,
    category: "english",
    instructor: "John Smith",
    duration: "3 tháng",
    level: "Intermediate"
  },
  {
    id: 2,
    name: "React & Next.js cho người mới bắt đầu",
    price: 799000,
    image: "https://picsum.photos/300/200?random=2",
    shortDescription: "Học React từ zero đến hero",
    fullDescription: "Khóa học React & Next.js từ cơ bản đến nâng cao. Xây dựng ứng dụng thực tế, deploy lên production.",
    rating: 4.9,
    reviews: 512,
    category: "programming",
    instructor: "Nguyễn Văn A",
    duration: "2 tháng",
    level: "Beginner"
  },
  {
    id: 3,
    name: "Digital Marketing chuyên nghiệp",
    price: 1200000,
    image: "https://picsum.photos/300/200?random=3",
    shortDescription: "Làm chủ Digital Marketing trong 60 ngày",
    fullDescription: "Khóa học Digital Marketing toàn diện: SEO, Google Ads, Facebook Ads, Content Marketing.",
    rating: 4.7,
    reviews: 189,
    category: "marketing",
    instructor: "Maria Johnson",
    duration: "2 tháng",
    level: "All levels"
  },
  {
    id: 4,
    name: "Python cho Data Science",
    price: 1800000,
    image: "https://picsum.photos/300/200?random=4",
    shortDescription: "Phân tích dữ liệu với Python",
    fullDescription: "Học Python cho Data Science: NumPy, Pandas, Matplotlib, Machine Learning cơ bản.",
    rating: 4.9,
    reviews: 367,
    category: "programming",
    instructor: "Dr. David Lee",
    duration: "3 tháng",
    level: "Intermediate"
  },
  {
    id: 5,
    name: "Giao tiếp tiếng Anh thương mại",
    price: 450000,
    image: "https://picsum.photos/300/200?random=5",
    shortDescription: "Business English cho dân văn phòng",
    fullDescription: "Nâng cao kỹ năng giao tiếp tiếng Anh trong môi trường công sở, viết email chuyên nghiệp.",
    rating: 4.6,
    reviews: 145,
    category: "english",
    instructor: "Sarah Wilson",
    duration: "1 tháng",
    level: "Intermediate"
  },
  {
    id: 6,
    name: "UI/UX Design với Figma",
    price: 950000,
    image: "https://picsum.photos/300/200?random=6",
    shortDescription: "Thiết kế giao diện chuyên nghiệp",
    fullDescription: "Học thiết kế UI/UX từ cơ bản đến nâng cao với Figma. Thực hành dự án thực tế.",
    rating: 4.8,
    reviews: 298,
    category: "design",
    instructor: "Alex Chen",
    duration: "2 tháng",
    level: "Beginner"
  }
];